import type { PulseCountry } from "./country-types";
import { OTHER_ROAMING } from "./country-types";

const visaInfo =
  "Los requisitos dependen de tu nacionalidad, pasaporte, motivo y fechas del viaje. Verifica los requisitos de entrada y tránsito con fuentes oficiales para tu pasaporte y fechas antes de reservar.";

export const AMERICAS_COUNTRIES: PulseCountry[] = [
  {
    countryCode: "US",
    countryName: "Estados Unidos",
    tokens: [
      "estados unidos", "united states", "usa", "eeuu", "ee uu",
      "new york", "nueva york", "los angeles", "san francisco", "washington dc",
      "chicago", "miami", "boston", "las vegas", "new mexico",
    ],
    plugType: "A / B",
    voltage: "120 V / 60 Hz",
    currency: "Dólar estadounidense",
    currencyCode: "USD",
    tippingPolicy: "La propina es habitual en algunos servicios, especialmente en restaurantes con servicio; comprueba si ya se añadió un cargo y considera que las prácticas varían.",
    paymentPreference: "Las tarjetas y pagos sin contacto son habituales; lleva una alternativa y algo de efectivo para lugares que no acepten tarjeta.",
    transportApps: ["Uber", "Lyft"],
    tapWater: "Potable",
    tapWaterAdvice: "La calidad y los avisos pueden variar por localidad; consulta las indicaciones de la autoridad local del agua antes de beber agua del grifo.",
    emergencyNumbers: { police: "911", ambulance: "911" },
    emergencySourceUrl: "https://www.911.gov/calling-911/",
    visaInfo: "Comprueba si necesitas ESTA o visado según tu pasaporte, ruta y fechas; revisa también los trámites de aduanas y tránsito en fuentes oficiales.",
    roaming: OTHER_ROAMING,
  },
  {
    countryCode: "CA",
    countryName: "Canadá",
    tokens: [
      "canada", "canadá", "toronto", "vancouver", "montreal", "montréal",
      "ottawa", "quebec city", "ciudad de quebec", "calgary", "edmonton",
    ],
    plugType: "A / B",
    voltage: "120 V / 60 Hz",
    currency: "Dólar canadiense",
    currencyCode: "CAD",
    tippingPolicy: "Puede dejarse propina por algunos servicios, como restaurantes con servicio; las prácticas y cargos incluidos varían.",
    paymentPreference: "Tarjetas y pagos sin contacto son habituales; conserva una alternativa y algo de efectivo para pequeños comercios.",
    transportApps: ["Uber", "Lyft"],
    tapWater: "Consultar",
    tapWaterAdvice: "La calidad y los avisos pueden variar por localidad; consulta las indicaciones de la autoridad local del agua antes de beber agua del grifo.",
    emergencyNumbers: { police: "911", ambulance: "911" },
    emergencySourceUrl: "https://parks.canada.ca/voyage-travel/securite-safety/urgence-emergency",
    visaInfo: "Comprueba si necesitas eTA o visado según tu pasaporte, forma de entrada y fechas; verifica el tránsito en fuentes oficiales.",
    roaming: OTHER_ROAMING,
  },
  {
    countryCode: "MX",
    countryName: "México",
    tokens: [
      "mexico", "méxico", "mexico city", "ciudad de mexico", "ciudad de méxico",
      "cdmx", "guadalajara", "monterrey", "cancun", "cancún", "oaxaca",
    ],
    plugType: "A / B",
    voltage: "127 V / 60 Hz",
    currency: "Peso mexicano",
    currencyCode: "MXN",
    tippingPolicy: "En algunos servicios, como restaurantes, puede esperarse o apreciarse una propina; revisa la cuenta y las costumbres locales, que varían.",
    paymentPreference: "Las tarjetas se aceptan en muchos establecimientos, pero el efectivo sigue siendo útil, especialmente en comercios pequeños.",
    transportApps: ["Uber", "DiDi"],
    tapWater: "Consultar",
    tapWaterAdvice: "La seguridad del agua del grifo no se debe asumir para todo el país; consulta indicaciones locales y el alojamiento.",
    emergencyNumbers: { police: "911", ambulance: "911" },
    emergencySourceUrl: "https://www.gob.mx/911",
    visaInfo,
    roaming: OTHER_ROAMING,
  },
  {
    countryCode: "BR",
    countryName: "Brasil",
    tokens: [
      "brasil", "brazil", "sao paulo", "são paulo", "rio de janeiro",
      "brasilia", "brasília", "salvador brasil", "recife", "curitiba",
    ],
    plugType: "N (enchufes C compatibles)",
    voltage: "127 / 220 V / 60 Hz (varía por localidad)",
    currency: "Real brasileño",
    currencyCode: "BRL",
    tippingPolicy: "Algunos establecimientos pueden incluir un cargo por servicio; comprueba la cuenta. Las prácticas adicionales varían según el lugar y el servicio.",
    paymentPreference: "Tarjetas y pagos digitales son comunes en muchas zonas; lleva una alternativa y algo de efectivo, especialmente fuera de grandes centros.",
    transportApps: ["Uber", "99"],
    tapWater: "Consultar",
    tapWaterAdvice: "La seguridad del agua del grifo puede variar por localidad; consulta las indicaciones locales antes de beberla.",
    emergencyNumbers: { police: "190", ambulance: "192" },
    emergencySourceUrl: "https://www.gov.uk/foreign-travel-advice/brazil/getting-help",
    visaInfo,
    roaming: OTHER_ROAMING,
  },
  {
    countryCode: "AR",
    countryName: "Argentina",
    tokens: [
      "argentina", "buenos aires", "cordoba argentina", "córdoba argentina",
      "mendoza", "rosario argentina", "bariloche", "salta argentina",
    ],
    plugType: "I (enchufes C también son comunes)",
    voltage: "230 V / 50 Hz",
    currency: "Peso argentino",
    currencyCode: "ARS",
    tippingPolicy: "En algunos servicios puede dejarse propina; revisa si hay cargos incluidos y ten en cuenta que las costumbres varían.",
    paymentPreference: "La aceptación de tarjetas y pagos digitales varía; lleva efectivo y un medio de pago alternativo.",
    transportApps: ["Uber", "Cabify"],
    tapWater: "Consultar",
    tapWaterAdvice: "La calidad y los avisos pueden variar por localidad; consulta indicaciones locales antes de beber agua del grifo.",
    emergencyNumbers: { police: "911", ambulance: "911" },
    emergencySourceUrl: "https://www.argentina.gob.ar/tema/emergencias",
    visaInfo,
    roaming: OTHER_ROAMING,
  },
  {
    countryCode: "CR",
    countryName: "Costa Rica",
    tokens: [
      "costa rica", "san jose costa rica", "san josé costa rica",
      "liberia costa rica", "tamarindo", "puerto viejo costa rica",
    ],
    plugType: "A / B",
    voltage: "120 V / 60 Hz",
    currency: "Colón costarricense",
    currencyCode: "CRC",
    tippingPolicy: "Comprueba si la cuenta incluye un cargo por servicio; cualquier propina adicional depende del servicio y las costumbres locales.",
    paymentPreference: "Las tarjetas se aceptan en muchos negocios, aunque el efectivo puede ser útil en comercios pequeños y zonas rurales.",
    transportApps: ["Uber"],
    tapWater: "Consultar",
    tapWaterAdvice: "La seguridad del agua del grifo puede variar por localidad y condiciones; consulta avisos locales y el alojamiento.",
    emergencyNumbers: { police: "911", ambulance: "911" },
    emergencySourceUrl: "https://www.gov.uk/foreign-travel-advice/costa-rica/getting-help",
    visaInfo,
    roaming: OTHER_ROAMING,
  },
  {
    countryCode: "PE",
    countryName: "Perú",
    tokens: [
      "peru", "perú", "lima peru", "cusco", "cuzco", "arequipa",
      "trujillo peru", "iquitos",
    ],
    plugType: "A / B / C",
    voltage: "230 V / 60 Hz",
    currency: "Sol",
    currencyCode: "PEN",
    tippingPolicy: "Las costumbres varían según el establecimiento y el servicio; revisa si hay cargos incluidos y decide según el contexto.",
    paymentPreference: "Las tarjetas se aceptan en muchos establecimientos urbanos; lleva efectivo para mercados, pequeños comercios y algunas zonas.",
    transportApps: ["Uber", "Cabify"],
    tapWater: "Consultar",
    tapWaterAdvice: "No asumas que el agua del grifo es segura en todo el país; consulta las indicaciones locales antes de beberla.",
    emergencyNumbers: { police: "105", ambulance: "106" },
    emergencySourceUrl: "https://www.gov.uk/foreign-travel-advice/peru/getting-help",
    visaInfo,
    roaming: OTHER_ROAMING,
  },
  {
    countryCode: "CO",
    countryName: "Colombia",
    tokens: [
      "colombia", "bogota", "bogotá", "medellin", "medellín", "cartagena colombia",
      "cali colombia", "barranquilla colombia",
    ],
    plugType: "A / B",
    voltage: "110 V / 60 Hz",
    currency: "Peso colombiano",
    currencyCode: "COP",
    tippingPolicy: "Algunos establecimientos pueden incluir un cargo de servicio opcional; revisa la cuenta y las costumbres locales.",
    paymentPreference: "Las tarjetas son aceptadas en muchos lugares, pero lleva efectivo y un medio de pago alternativo.",
    transportApps: ["Uber", "DiDi"],
    tapWater: "Consultar",
    tapWaterAdvice: "La seguridad del agua del grifo puede variar por localidad; consulta los avisos locales y las indicaciones del alojamiento.",
    emergencyNumbers: { police: "123", ambulance: "123" },
    emergencySourceUrl: "https://www.gov.uk/foreign-travel-advice/colombia/getting-help",
    visaInfo,
    roaming: OTHER_ROAMING,
  },
];