import type { PulseCountry } from "./country-types";
import { OTHER_ROAMING } from "./country-types";

const WATER_ADVICE =
  "La seguridad del agua puede variar por localidad, edificio y avisos temporales. Consulta las indicaciones locales antes de beber agua del grifo; en zonas rurales o con suministro privado, verifica con el alojamiento o usa agua embotellada o tratada si no puedes confirmarlo.";

const VISA_INFO =
  "Comprueba los requisitos de entrada y tránsito para tu pasaporte, propósito y fechas exactas con las autoridades oficiales antes de reservar y viajar. La exención de visado, si existe, depende de la nacionalidad y las condiciones aplicables.";

export const ASIA_OCEANIA_COUNTRIES: PulseCountry[] = [
  {
    countryCode: "JP",
    countryName: "Japón",
    tokens: ["japón", "japon", "japan", "tokio", "tokyo", "osaka", "kioto", "kyoto", "sapporo"],
    plugType: "A / B",
    voltage: "100 V / 50–60 Hz",
    currency: "Yen japonés",
    currencyCode: "JPY",
    tippingPolicy: "No suele dejarse propina; las costumbres pueden variar según el servicio.",
    paymentPreference: "Las tarjetas se aceptan ampliamente en ciudades, pero lleva algo de efectivo para comercios pequeños y lugares que no acepten tarjeta.",
    transportApps: ["GO", "Uber"],
    tapWater: "Potable",
    tapWaterAdvice: "Generalmente potable en la red pública; respeta avisos locales y las indicaciones del alojamiento.",
    emergencyNumbers: { police: "110", ambulance: "119" },
    emergencySourceUrl: "https://www.japan.travel/en/plan/hotline/",
    visaInfo: "Revisa si necesitas visado y los trámites de entrada y aduanas para tu pasaporte y fechas; consulta Visit Japan Web si corresponde.",
    roaming: OTHER_ROAMING,
  },
  {
    countryCode: "CN",
    countryName: "China",
    tokens: ["china", "beijing", "pekin", "pequín", "shanghai", "shanghái", "guangzhou"],
    plugType: "A / I (tomas híbridas)",
    voltage: "230 V / 50 Hz",
    currency: "Yuan renminbi",
    currencyCode: "CNY",
    tippingPolicy: "La propina no suele ser habitual; las prácticas pueden variar por establecimiento y servicio.",
    paymentPreference: "Los pagos móviles son muy comunes; verifica de antemano qué medios aceptan visitantes y lleva una alternativa, como efectivo o tarjeta.",
    transportApps: ["DiDi"],
    tapWater: "Consultar",
    tapWaterAdvice: WATER_ADVICE,
    emergencyNumbers: { police: "110", ambulance: "120" },
    emergencySourceUrl: "https://www.gov.uk/foreign-travel-advice/china/getting-help",
    visaInfo: VISA_INFO,
    roaming: OTHER_ROAMING,
  },
  {
    countryCode: "TH",
    countryName: "Tailandia",
    tokens: ["tailandia", "thailand", "bangkok", "phuket", "chiang mai", "chiangmai"],
    plugType: "C / O (A / B también pueden encontrarse)",
    voltage: "230 V / 50 Hz",
    currency: "Baht tailandés",
    currencyCode: "THB",
    tippingPolicy: "No hay una regla única; algunos viajeros dejan algo extra por buen servicio, según el lugar.",
    paymentPreference: "Tarjetas habituales en hoteles y comercios urbanos; el efectivo sigue siendo útil para mercados, puestos y pequeños negocios.",
    transportApps: ["Grab", "Bolt"],
    tapWater: "Consultar",
    tapWaterAdvice: WATER_ADVICE,
    emergencyNumbers: { police: "191", ambulance: "1669" },
    emergencySourceUrl: "https://www.gov.uk/foreign-travel-advice/thailand/getting-help",
    visaInfo: VISA_INFO,
    roaming: OTHER_ROAMING,
  },
  {
    countryCode: "ID",
    countryName: "Indonesia (Bali)",
    tokens: ["indonesia", "bali", "denpasar", "ubud", "jakarta"],
    plugType: "C / F",
    voltage: "230 V / 50 Hz",
    currency: "Rupia indonesia",
    currencyCode: "IDR",
    tippingPolicy: "Las prácticas varían; revisa si el servicio o cargo ya está incluido antes de dejar algo adicional.",
    paymentPreference: "Las tarjetas se aceptan en muchos establecimientos urbanos y turísticos; lleva efectivo para pequeños comercios y algunas zonas fuera de las ciudades.",
    transportApps: ["Gojek", "Grab"],
    tapWater: "Consultar",
    tapWaterAdvice: WATER_ADVICE,
    emergencyNumbers: { police: "110", ambulance: "118" },
    emergencySourceUrl: "https://www.gov.uk/foreign-travel-advice/indonesia/getting-help",
    visaInfo: VISA_INFO,
    roaming: OTHER_ROAMING,
  },
  {
    countryCode: "VN",
    countryName: "Vietnam",
    tokens: ["vietnam", "viet nam", "hanoi", "hanói", "ho chi minh city", "ciudad ho chi minh", "saigon", "saigón", "da nang"],
    plugType: "A / B / C",
    voltage: "230 V / 50 Hz",
    currency: "Dong vietnamita",
    currencyCode: "VND",
    tippingPolicy: "No hay una expectativa uniforme; puede variar por tipo de servicio y establecimiento.",
    paymentPreference: "El efectivo sigue siendo útil, especialmente en mercados y negocios pequeños; consulta si se aceptan tarjetas antes de pagar.",
    transportApps: ["Grab", "Xanh SM"],
    tapWater: "Consultar",
    tapWaterAdvice: WATER_ADVICE,
    emergencyNumbers: { police: "113", ambulance: "115" },
    emergencySourceUrl: "https://www.gov.uk/foreign-travel-advice/vietnam/getting-help",
    visaInfo: VISA_INFO,
    roaming: OTHER_ROAMING,
  },
  {
    countryCode: "KR",
    countryName: "Corea del Sur",
    tokens: ["corea del sur", "south korea", "republic of korea", "seul", "seoul", "busan", "pusan", "incheon"],
    plugType: "C / F",
    voltage: "230 V / 60 Hz",
    currency: "Won surcoreano",
    currencyCode: "KRW",
    tippingPolicy: "La propina no suele ser habitual; las prácticas pueden variar según el establecimiento.",
    paymentPreference: "Las tarjetas son ampliamente aceptadas en ciudades; lleva un medio alternativo para pequeños comercios o situaciones puntuales.",
    transportApps: ["Kakao T", "Uber"],
    tapWater: "Consultar",
    tapWaterAdvice: WATER_ADVICE,
    emergencyNumbers: { police: "112", ambulance: "119" },
    emergencySourceUrl: "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=140042",
    visaInfo: VISA_INFO,
    roaming: OTHER_ROAMING,
  },
  {
    countryCode: "SG",
    countryName: "Singapur",
    tokens: ["singapur", "singapore"],
    plugType: "G",
    voltage: "230 V / 50 Hz",
    currency: "Dólar de Singapur",
    currencyCode: "SGD",
    tippingPolicy: "No hay una obligación general de dejar propina; comprueba si el establecimiento ya incluye cargos de servicio.",
    paymentPreference: "Tarjetas y pagos sin contacto son comunes; conserva una alternativa para pequeños comercios y puestos.",
    transportApps: ["Grab", "Gojek", "Tada"],
    tapWater: "Consultar",
    tapWaterAdvice: WATER_ADVICE,
    emergencyNumbers: { police: "999", ambulance: "995" },
    emergencySourceUrl: "https://www.gov.sg/contact-us",
    visaInfo: VISA_INFO,
    roaming: OTHER_ROAMING,
  },
  {
    countryCode: "AE",
    countryName: "Emiratos Árabes Unidos (Dubái)",
    tokens: ["emiratos arabes unidos", "emiratos árabes unidos", "united arab emirates", "uae", "dubai", "dubái", "abu dhabi"],
    plugType: "G",
    voltage: "230 V / 50 Hz",
    currency: "Dirham de los Emiratos Árabes Unidos",
    currencyCode: "AED",
    tippingPolicy: "Las prácticas varían; revisa si el cargo de servicio está incluido antes de dejar algo adicional.",
    paymentPreference: "Tarjetas y pagos sin contacto son habituales en ciudades; lleva una alternativa para pequeños establecimientos.",
    transportApps: ["Careem", "Uber"],
    tapWater: "Consultar",
    tapWaterAdvice: WATER_ADVICE,
    emergencyNumbers: { police: "999", ambulance: "998" },
    emergencySourceUrl: "https://u.ae/en/information-and-services/justice-safety-and-the-law/Safety/handling-emergencies",
    visaInfo: VISA_INFO,
    roaming: OTHER_ROAMING,
  },
  {
    countryCode: "AU",
    countryName: "Australia",
    tokens: ["australia", "sydney", "sídney", "melbourne", "brisbane", "canberra", "perth"],
    plugType: "I",
    voltage: "230 V / 50 Hz",
    currency: "Dólar australiano",
    currencyCode: "AUD",
    tippingPolicy: "La propina no es obligatoria; algunas personas dejan algo extra por buen servicio, según el contexto.",
    paymentPreference: "Las tarjetas y pagos sin contacto son comunes; lleva un medio de pago alternativo.",
    transportApps: ["Uber", "DiDi"],
    tapWater: "Consultar",
    tapWaterAdvice: WATER_ADVICE,
    emergencyNumbers: { police: "000", ambulance: "000" },
    emergencySourceUrl: "https://www.acma.gov.au/emergency-calls",
    visaInfo: "Comprueba si necesitas ETA, eVisitor u otro visado según tu pasaporte y fechas; verifica los requisitos de entrada en fuentes oficiales.",
    roaming: OTHER_ROAMING,
  },
  {
    countryCode: "NZ",
    countryName: "Nueva Zelanda",
    tokens: ["nueva zelanda", "new zealand", "auckland", "wellington", "christchurch", "queenstown"],
    plugType: "I",
    voltage: "230 V / 50 Hz",
    currency: "Dólar neozelandés",
    currencyCode: "NZD",
    tippingPolicy: "La propina no suele ser obligatoria; las prácticas pueden variar según el establecimiento y el servicio.",
    paymentPreference: "Las tarjetas se aceptan ampliamente; conserva una alternativa para pequeños comercios o zonas remotas.",
    transportApps: ["Uber"],
    tapWater: "Consultar",
    tapWaterAdvice: WATER_ADVICE,
    emergencyNumbers: { police: "111", ambulance: "111" },
    emergencySourceUrl: "https://www.govt.nz/browse/law-crime-and-justice/crimes-and-emergencies/111-emergency-service",
    visaInfo: "Comprueba si necesitas NZeTA o visado según tu pasaporte y fechas; verifica los requisitos de entrada en fuentes oficiales.",
    roaming: OTHER_ROAMING,
  },
];