import type { PulseCountry } from "./country-types";
import { EU_ROAMING, OTHER_ROAMING } from "./country-types";

const visaInfo =
  "Los requisitos dependen de tu nacionalidad, pasaporte, motivo y fechas del viaje. Verifica los requisitos de entrada y tránsito con fuentes oficiales para tu pasaporte y fechas antes de reservar.";

const europeanTapWater =
  "En la red pública suele ser potable; respeta los avisos locales y consulta si tu alojamiento usa un suministro privado.";

// Referencia de electricidad consultada: https://www.worldstandards.eu/electricity/plug-voltage-by-country/
// World Standards indica que esta tabla fue actualizada el 7 de septiembre de 2025; IEC retiró su guía.
export const EUROPE_COUNTRIES: PulseCountry[] = [
  {
    countryCode: "ES",
    countryName: "España",
    tokens: [
      "españa", "espana", "spain", "madrid", "barcelona", "sevilla", "seville",
      "valencia españa", "valencia spain", "malaga españa", "malaga spain",
    ],
    plugType: "C / F",
    voltage: "230 V / 50 Hz",
    currency: "Euro",
    currencyCode: "EUR",
    tippingPolicy: "La propina no es obligatoria; algunas personas redondean o dejan algo por buen servicio. Revisa si hay cargos incluidos; las costumbres varían.",
    paymentPreference: "Las tarjetas son habituales en muchos comercios; conserva un medio de pago alternativo y algo de efectivo para lugares que no acepten tarjeta.",
    transportApps: ["Cabify", "Uber", "FreeNow"],
    tapWater: "Potable",
    tapWaterAdvice: europeanTapWater,
    emergencyNumbers: { police: "112", ambulance: "112" },
    emergencySourceUrl: "https://digital-strategy.ec.europa.eu/en/policies/112",
    visaInfo,
    roaming: EU_ROAMING,
  },
  {
    countryCode: "FR",
    countryName: "Francia",
    tokens: [
      "francia", "france", "paris francia", "paris france", "lyon francia",
      "lyon france", "marsella", "marseille france", "niza francia", "nice france",
    ],
    plugType: "C / E",
    voltage: "230 V / 50 Hz",
    currency: "Euro",
    currencyCode: "EUR",
    tippingPolicy: "Comprueba si el servicio está incluido en la cuenta; cualquier extra es opcional y las costumbres varían según el lugar y el servicio.",
    paymentPreference: "Las tarjetas se aceptan en muchos establecimientos; lleva una alternativa y algo de efectivo para comercios pequeños.",
    transportApps: ["Uber", "G7", "Bolt"],
    tapWater: "Potable",
    tapWaterAdvice: europeanTapWater,
    emergencyNumbers: { police: "112", ambulance: "112" },
    emergencySourceUrl: "https://digital-strategy.ec.europa.eu/en/policies/112",
    visaInfo,
    roaming: EU_ROAMING,
  },
  {
    countryCode: "IT",
    countryName: "Italia",
    tokens: [
      "italia", "italy", "roma italia", "rome italy", "milan italy", "milano",
      "florencia italia", "florence italy", "napoles italia", "naples italy",
    ],
    plugType: "C / F / L",
    voltage: "230 V / 50 Hz",
    currency: "Euro",
    currencyCode: "EUR",
    tippingPolicy: "Las prácticas varían por región, establecimiento y servicio. Comprueba si hay cargos en la cuenta; cualquier propina adicional queda a tu criterio.",
    paymentPreference: "Las tarjetas se aceptan en muchos lugares; lleva efectivo de respaldo para pequeños comercios y zonas donde la aceptación puede variar.",
    transportApps: ["FreeNow", "itTaxi"],
    tapWater: "Potable",
    tapWaterAdvice: europeanTapWater,
    emergencyNumbers: { police: "112", ambulance: "112" },
    emergencySourceUrl: "https://digital-strategy.ec.europa.eu/en/policies/112",
    visaInfo,
    roaming: EU_ROAMING,
  },
  {
    countryCode: "PT",
    countryName: "Portugal",
    tokens: [
      "portugal", "lisboa", "lisbon", "oporto", "porto portugal",
      "coimbra portugal", "faro portugal",
    ],
    plugType: "C / F",
    voltage: "230 V / 50 Hz",
    currency: "Euro",
    currencyCode: "EUR",
    tippingPolicy: "La propina es opcional y las prácticas varían según el servicio y el lugar; revisa la cuenta por si incluye cargos.",
    paymentPreference: "Las tarjetas son habituales en muchos comercios, aunque puede ser útil llevar efectivo para pequeños establecimientos y pagos locales.",
    transportApps: ["Bolt", "Uber"],
    tapWater: "Potable",
    tapWaterAdvice: europeanTapWater,
    emergencyNumbers: { police: "112", ambulance: "112" },
    emergencySourceUrl: "https://digital-strategy.ec.europa.eu/en/policies/112",
    visaInfo,
    roaming: EU_ROAMING,
  },
  {
    countryCode: "GB",
    countryName: "Reino Unido",
    tokens: [
      "reino unido", "united kingdom", "uk", "great britain", "gran bretaña",
      "londres", "london", "edimburgo", "edinburgh", "manchester", "birmingham reino unido",
    ],
    plugType: "G",
    voltage: "230 V / 50 Hz",
    currency: "Libra esterlina",
    currencyCode: "GBP",
    tippingPolicy: "En algunos restaurantes puede añadirse un cargo por servicio; comprueba la cuenta. Cualquier propina adicional es opcional y las costumbres varían.",
    paymentPreference: "Tarjetas y pagos sin contacto son habituales en muchos lugares; conserva una alternativa y algo de efectivo.",
    transportApps: ["Uber", "FreeNow"],
    tapWater: "Potable",
    tapWaterAdvice: europeanTapWater,
    emergencyNumbers: { police: "999 / 112", ambulance: "999 / 112" },
    emergencySourceUrl: "https://www.gov.uk/guidance/999-and-112-the-uks-national-emergency-numbers",
    visaInfo: "Comprueba si necesitas ETA o visado según tu pasaporte y fechas; revisa también los requisitos de tránsito y aduanas en fuentes oficiales.",
    roaming: OTHER_ROAMING,
  },
  {
    countryCode: "DE",
    countryName: "Alemania",
    tokens: [
      "alemania", "germany", "berlin", "berlín", "munich", "múnich", "muenchen",
      "hamburgo", "hamburg germany", "frankfurt alemania", "frankfurt germany",
    ],
    plugType: "C / F",
    voltage: "230 V / 50 Hz",
    currency: "Euro",
    currencyCode: "EUR",
    tippingPolicy: "En algunos servicios se suele redondear o dejar algo extra, pero las prácticas varían. Comprueba la cuenta y decide según el contexto.",
    paymentPreference: "Las tarjetas se aceptan en muchos negocios, pero el efectivo sigue siendo útil en pequeños comercios; lleva un medio alternativo.",
    transportApps: ["FreeNow", "Bolt", "Uber"],
    tapWater: "Potable",
    tapWaterAdvice: europeanTapWater,
    emergencyNumbers: { police: "112", ambulance: "112" },
    emergencySourceUrl: "https://digital-strategy.ec.europa.eu/en/policies/112",
    visaInfo,
    roaming: EU_ROAMING,
  },
  {
    countryCode: "NL",
    countryName: "Países Bajos",
    tokens: [
      "paises bajos", "países bajos", "netherlands", "holanda", "holland",
      "amsterdam", "rotterdam", "la haya", "the hague", "utrecht paises bajos",
    ],
    plugType: "C / F",
    voltage: "230 V / 50 Hz",
    currency: "Euro",
    currencyCode: "EUR",
    tippingPolicy: "La propina no es obligatoria; algunas personas redondean o dejan algo por buen servicio. Las prácticas y cargos incluidos varían.",
    paymentPreference: "Los pagos con tarjeta y débito son comunes; la aceptación de cada medio puede variar por comercio, así que lleva una alternativa.",
    transportApps: ["Uber", "Bolt"],
    tapWater: "Potable",
    tapWaterAdvice: europeanTapWater,
    emergencyNumbers: { police: "112", ambulance: "112" },
    emergencySourceUrl: "https://digital-strategy.ec.europa.eu/en/policies/112",
    visaInfo,
    roaming: EU_ROAMING,
  },
  {
    countryCode: "BE",
    countryName: "Bélgica",
    tokens: [
      "belgica", "bélgica", "belgium", "bruselas", "brussels", "amberes",
      "antwerp", "gante", "ghent", "brujas belgica", "bruges belgium",
    ],
    plugType: "C / E",
    voltage: "230 V / 50 Hz",
    currency: "Euro",
    currencyCode: "EUR",
    tippingPolicy: "Comprueba si se incluyen cargos por servicio; cualquier propina adicional depende del servicio y de las costumbres locales.",
    paymentPreference: "Las tarjetas se aceptan en muchos comercios; lleva una alternativa y efectivo para establecimientos que no acepten tu medio habitual.",
    transportApps: ["Uber", "Bolt"],
    tapWater: "Potable",
    tapWaterAdvice: europeanTapWater,
    emergencyNumbers: { police: "112", ambulance: "112" },
    emergencySourceUrl: "https://digital-strategy.ec.europa.eu/en/policies/112",
    visaInfo,
    roaming: EU_ROAMING,
  },
  {
    countryCode: "CH",
    countryName: "Suiza",
    tokens: [
      "suiza", "switzerland", "zurich", "zúrich", "geneva", "ginebra",
      "bern", "berna", "basel", "basilea", "lausanne", "lausana",
    ],
    plugType: "C / J",
    voltage: "230 V / 50 Hz",
    currency: "Franco suizo",
    currencyCode: "CHF",
    tippingPolicy: "El servicio suele estar incluido, pero las prácticas varían; comprueba la cuenta y decide si deseas dejar algo adicional.",
    paymentPreference: "Las tarjetas se aceptan en muchos lugares; lleva un medio de pago alternativo y algo de efectivo para comercios pequeños.",
    transportApps: ["Uber", "FreeNow"],
    tapWater: "Consultar",
    tapWaterAdvice: europeanTapWater,
    emergencyNumbers: { police: "117", ambulance: "144" },
    emergencySourceUrl: "https://www.ch.ch/en/safety-and-justice/emergencies-and-danger",
    visaInfo,
    roaming: OTHER_ROAMING,
  },
  {
    countryCode: "GR",
    countryName: "Grecia",
    tokens: [
      "grecia", "greece", "atenas", "athens", "salonica", "thessaloniki",
      "heraklion grecia", "heraklion greece", "santorini grecia", "santorini greece",
    ],
    plugType: "C / F",
    voltage: "230 V / 50 Hz",
    currency: "Euro",
    currencyCode: "EUR",
    tippingPolicy: "Las costumbres varían según el lugar y el servicio; revisa la cuenta por si hay cargos incluidos. Cualquier extra queda a tu criterio.",
    paymentPreference: "Las tarjetas se aceptan en muchos comercios, aunque la disponibilidad puede variar, especialmente en negocios pequeños; lleva efectivo de respaldo.",
    transportApps: ["Uber", "Bolt"],
    tapWater: "Consultar",
    tapWaterAdvice: europeanTapWater,
    emergencyNumbers: { police: "112", ambulance: "112" },
    emergencySourceUrl: "https://digital-strategy.ec.europa.eu/en/policies/112",
    visaInfo,
    roaming: EU_ROAMING,
  },
  {
    countryCode: "AT",
    countryName: "Austria",
    tokens: [
      "austria", "viena", "vienna", "salzburgo", "salzburg", "innsbruck",
      "graz austria", "linz austria",
    ],
    plugType: "C / F",
    voltage: "230 V / 50 Hz",
    currency: "Euro",
    currencyCode: "EUR",
    tippingPolicy: "En algunos servicios se suele redondear o dejar algo extra; las prácticas varían. Revisa la cuenta por si hay cargos incluidos.",
    paymentPreference: "Las tarjetas son habituales en muchos establecimientos, pero lleva efectivo y un medio de pago alternativo para pequeños comercios.",
    transportApps: ["FreeNow", "Bolt"],
    tapWater: "Potable",
    tapWaterAdvice: europeanTapWater,
    emergencyNumbers: { police: "112", ambulance: "112" },
    emergencySourceUrl: "https://digital-strategy.ec.europa.eu/en/policies/112",
    visaInfo,
    roaming: EU_ROAMING,
  },
  {
    countryCode: "IE",
    countryName: "Irlanda",
    tokens: [
      "irlanda", "ireland", "dublin", "dublín", "cork irlanda", "cork ireland",
      "galway irlanda", "galway ireland", "limerick irlanda", "limerick ireland",
    ],
    plugType: "G",
    voltage: "230 V / 50 Hz",
    currency: "Euro",
    currencyCode: "EUR",
    tippingPolicy: "Las prácticas varían por establecimiento y servicio. Comprueba si hay un cargo por servicio incluido; cualquier propina adicional es opcional.",
    paymentPreference: "Las tarjetas y pagos sin contacto son comunes en muchos lugares; conserva una alternativa y algo de efectivo.",
    transportApps: ["FreeNow", "Uber"],
    tapWater: "Consultar",
    tapWaterAdvice: europeanTapWater,
    emergencyNumbers: { police: "112", ambulance: "112" },
    emergencySourceUrl: "https://digital-strategy.ec.europa.eu/en/policies/112",
    visaInfo,
    roaming: EU_ROAMING,
  },
  {
    countryCode: "NO",
    countryName: "Noruega",
    tokens: [
      "noruega", "norway", "oslo", "bergen noruega", "bergen norway",
      "trondheim noruega", "trondheim norway", "stavanger noruega", "stavanger norway",
    ],
    plugType: "C / F",
    voltage: "230 V / 50 Hz",
    currency: "Corona noruega",
    currencyCode: "NOK",
    tippingPolicy: "La propina no es obligatoria; las prácticas varían y cualquier extra depende del servicio y del contexto.",
    paymentPreference: "Las tarjetas y pagos electrónicos son habituales, aunque la aceptación puede variar por comercio; conserva un medio de pago alternativo.",
    transportApps: ["Uber"],
    tapWater: "Consultar",
    tapWaterAdvice: europeanTapWater,
    emergencyNumbers: { police: "112", ambulance: "113" },
    emergencySourceUrl: "https://www.gov.uk/foreign-travel-advice/norway/getting-help",
    visaInfo,
    roaming: EU_ROAMING,
  },
  {
    countryCode: "IS",
    countryName: "Islandia",
    tokens: [
      "islandia", "iceland", "reikiavik", "reykjavik", "akureyri",
      "keflavik islandia", "keflavik iceland", "selfoss islandia", "selfoss iceland",
    ],
    plugType: "C / F",
    voltage: "230 V / 50 Hz",
    currency: "Corona islandesa",
    currencyCode: "ISK",
    tippingPolicy: "La propina no suele ser obligatoria; comprueba la cuenta y considera que las prácticas varían según el servicio.",
    paymentPreference: "Las tarjetas se aceptan en muchos lugares, pero conserva un medio de pago alternativo para cualquier incidencia o comercio con aceptación limitada.",
    transportApps: ["Hreyfill"],
    tapWater: "Consultar",
    tapWaterAdvice: europeanTapWater,
    emergencyNumbers: { police: "112", ambulance: "112" },
    emergencySourceUrl: "https://www.112.is/en/112",
    visaInfo,
    roaming: EU_ROAMING,
  },
];