import type { PulseCountry } from "./country-types";
import { OTHER_ROAMING } from "./country-types";

export const AFRICA_COUNTRIES: PulseCountry[] = [
  {
    countryCode: "MA",
    countryName: "Marruecos",
    tokens: [
      "marruecos", "morocco", "casablanca marruecos", "casablanca morocco",
      "marrakech marruecos", "marrakech morocco", "fez marruecos", "fes morocco",
      "rabat marruecos", "rabat morocco", "tanger marruecos", "tangier morocco",
    ],
    plugType: "C / E",
    voltage: "230 V / 50 Hz",
    currency: "Dirham marroquí (MAD)",
    currencyCode: "MAD",
    tippingPolicy: "La propina no es obligatoria; en algunos servicios se suele dejar algo si se desea. Comprueba si ya se ha añadido un cargo y considera que las prácticas varían.",
    paymentPreference: "Las tarjetas se aceptan en muchos hoteles y comercios urbanos; lleva dirhams en efectivo para mercados, pequeños comercios y lugares con aceptación limitada de tarjeta.",
    transportApps: ["inDrive"],
    tapWater: "Consultar",
    tapWaterAdvice: "No se puede afirmar la seguridad del agua del grifo en todo el país; consulta en tu alojamiento o con las autoridades locales.",
    emergencyNumbers: { police: "190", ambulance: "150" },
    emergencySourceUrl: "https://www.gov.uk/foreign-travel-advice/morocco/getting-help",
    visaInfo: "Comprueba los requisitos de entrada y visado para tu nacionalidad, pasaporte y fechas exactas del viaje en fuentes oficiales antes de reservar y viajar.",
    roaming: OTHER_ROAMING,
  },
  {
    countryCode: "EG",
    countryName: "Egipto",
    tokens: [
      "egipto", "egypt", "el cairo egipto", "cairo egypt", "alejandria egipto",
      "alexandria egypt", "giza egipto", "giza egypt", "luxor egipto", "luxor egypt",
      "asuan egipto", "aswan egypt",
    ],
    plugType: "C / F",
    voltage: "230 V / 50 Hz",
    currency: "Libra egipcia (EGP)",
    currencyCode: "EGP",
    tippingPolicy: "Las propinas son comunes en algunos servicios, pero las prácticas varían. Comprueba si el cargo de servicio está incluido y decide según el servicio recibido.",
    paymentPreference: "Las tarjetas se aceptan en muchos hoteles y comercios grandes; lleva libras egipcias en efectivo para comercios pequeños, mercados y otros pagos que no acepten tarjeta.",
    transportApps: ["Uber", "Careem"],
    tapWater: "Consultar",
    tapWaterAdvice: "No se puede afirmar la seguridad del agua del grifo en todo el país; consulta en tu alojamiento o con las autoridades locales.",
    emergencyNumbers: { police: "122", ambulance: "123" },
    emergencySourceUrl: "https://www.gov.uk/foreign-travel-advice/egypt/getting-help",
    visaInfo: "Comprueba los requisitos de entrada y visado para tu nacionalidad, pasaporte y fechas exactas del viaje en fuentes oficiales antes de reservar y viajar.",
    roaming: OTHER_ROAMING,
  },
  {
    countryCode: "ZA",
    countryName: "Sudáfrica",
    tokens: [
      "sudafrica", "south africa", "ciudad del cabo sudafrica", "cape town south africa",
      "johannesburgo sudafrica", "johannesburg south africa", "durban sudafrica",
      "durban south africa", "pretoria sudafrica", "pretoria south africa",
    ],
    plugType: "C / M / N",
    voltage: "230 V / 50 Hz",
    currency: "Rand sudafricano (ZAR)",
    currencyCode: "ZAR",
    tippingPolicy: "En algunos servicios se suele dejar propina, pero no es una obligación universal. Comprueba si se ha añadido un cargo de servicio y considera que las prácticas varían.",
    paymentPreference: "Las tarjetas se aceptan ampliamente en ciudades y comercios grandes; lleva algo de efectivo para pequeños comercios y situaciones en que no se acepte tarjeta.",
    transportApps: ["Uber", "Bolt"],
    tapWater: "Consultar",
    tapWaterAdvice: "No se puede afirmar la seguridad del agua del grifo en todo el país; consulta en tu alojamiento o con las autoridades locales.",
    emergencyNumbers: { police: "10111", ambulance: "10177" },
    emergencySourceUrl: "https://www.gov.uk/foreign-travel-advice/south-africa/getting-help",
    visaInfo: "Comprueba los requisitos de entrada y visado para tu nacionalidad, pasaporte y fechas exactas del viaje en fuentes oficiales antes de reservar y viajar.",
    roaming: OTHER_ROAMING,
  },
];